# Generated by Django 4.1.7 on 2023-04-12 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City_name')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('company_name', models.CharField(max_length=50, verbose_name='Company_name')),
                ('fuel1', models.CharField(default='', max_length=50, verbose_name='AI-80')),
                ('fuel2', models.CharField(default='', max_length=50, verbose_name='AI-90')),
                ('fuel3', models.CharField(default='', max_length=50, verbose_name='AI-91')),
                ('fuel4', models.CharField(default='', max_length=50, verbose_name='AI-92')),
                ('fuel5', models.CharField(default='', max_length=50, verbose_name='AI-95')),
            ],
            options={
                'verbose_name': 'Fuel',
                'verbose_name_plural': 'Fuel',
            },
        ),
    ]
