# Generated by Django 4.1.7 on 2023-04-12 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fuel',
            old_name='feul2',
            new_name='fuel2',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='feul3',
            new_name='fuel3',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='feul4',
            new_name='fuel4',
        ),
        migrations.RenameField(
            model_name='fuel',
            old_name='feul5',
            new_name='fuel5',
        ),
    ]
