# Generated by Django 4.1.7 on 2023-04-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City_name')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('ai_80', models.CharField(default='', max_length=50, verbose_name='fuel')),
                ('ai_90', models.CharField(default='', max_length=50, verbose_name='fuel')),
                ('ai_91', models.CharField(default='', max_length=50, verbose_name='fuel')),
                ('ai_92', models.CharField(default='', max_length=50, verbose_name='fuel')),
                ('ai_98', models.CharField(default='', max_length=50, verbose_name='fuel')),
            ],
            options={
                'verbose_name': 'city',
                'verbose_name_plural': 'city',
            },
        ),
    ]
