# Generated by Django 4.1.7 on 2023-04-03 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='City_name')),
                ('servise_name', models.CharField(max_length=50, verbose_name='Servise_name')),
                ('fuel1', models.CharField(default='', max_length=50, verbose_name='ai_80')),
                ('fuel2', models.CharField(default='', max_length=50, verbose_name='ai_90')),
                ('fuel3', models.CharField(default='', max_length=50, verbose_name='ai_91')),
                ('fuel4', models.CharField(default='', max_length=50, verbose_name='ai_92')),
                ('fuel5', models.CharField(default='', max_length=50, verbose_name='ai_98')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'City',
            },
        ),
    ]
