# Generated by Django 4.1.7 on 2023-04-03 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='servise_name',
            new_name='url',
        ),
    ]
